channels:
- conda-forge
dependencies:
- python=3.8.10
- pip>=20.0.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.1
  - numpy==1.24.4
  - packaging==23.2
  - pyyaml==6.0.2
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
